# Generated by Django 5.2.8 on 2025-11-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('algorithm_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering'), ('dimensionality', 'Dimensionality Reduction'), ('neural', 'Neural Networks')], max_length=50)),
                ('short_description', models.TextField()),
                ('implementation_code', models.TextField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('use_cases', models.TextField()),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comparison_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithms', models.ManyToManyField(to='algorithms.mlalgorithm')),
            ],
        ),
    ]
