# Generated by Django 5.2.8 on 2025-11-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlalgorithm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mlalgorithm',
            name='wikipedia_url',
            field=models.URLField(blank=True, help_text='Wikipedia page URL for this algorithm', null=True),
        ),
        migrations.AlterField(
            model_name='mlalgorithm',
            name='algorithm_type',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering'), ('dimensionality', 'Dimensionality Reduction'), ('neural', 'Neural Networks'), ('ensemble', 'Ensemble Methods')], max_length=50),
        ),
    ]
